apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
