apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: other-data
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: ""
  volumeName: other-data