apiVersion: v1
kind: Pod
metadata:
  generateName: data-writer
spec:
  volumes:
  - name: efs-pv
    persistentVolumeClaim:
      claimName: efs-claim
  containers:
  - name: writer
    image: busybox
    command:
    - sh
    - -c
    - |
      echo "A writer pod wrote this." > /other-data/${HOSTNAME} && 
      echo "I can write to /other-data/${HOSTNAME}." ;
      sleep 9999
    volumeMounts:
    - name: efs-pv
      mountPath: /other-data
    resources:
      requests:
        cpu: 1m 
