apiVersion: v1
kind: Pod
metadata:
  name: kiada
spec:
  containers:
  - name: kiada
    image: pvmtriet233/kiada:0.1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
  initContainer:
  - name: test
    image: mysql:latest 
