apiVersion: v1
kind: Pod
metadata:
  name: kiada-stdin
spec:
  containers:
  - name: kiada
    image: pvmtriet233/kiada:0.2
    imagePullPolicy: Always
    stdin: true
    ports:
    - containerPort: 8080
