apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: snippetbox
  name: snippetbox
spec:
  containers:
  - image: ghcr.io/pvmtriet232/snippetbox2:main
    name: snippetbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
